# Generated by Django 3.2.6 on 2021-08-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrec_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipein',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='swipeout',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
