# Generated by Django 3.2.6 on 2021-08-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrec_api', '0002_auto_20210808_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swipein_id', models.IntegerField()),
                ('swipeout_id', models.IntegerField()),
                ('travel_time', models.IntegerField()),
            ],
        ),
    ]
