# Generated by Django 3.2.6 on 2021-08-09 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrec_api', '0003_travelhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SwipeIn',
        ),
        migrations.DeleteModel(
            name='SwipeOut',
        ),
        migrations.RemoveField(
            model_name='travelhistory',
            name='swipein_id',
        ),
        migrations.RemoveField(
            model_name='travelhistory',
            name='swipeout_id',
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='swipe_in_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='swipe_in_station_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='swipe_out_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='swipe_out_station_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='travel_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
