# Generated by Django 3.2.6 on 2021-08-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrec_api', '0004_auto_20210809_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelhistory',
            name='swipe_in_at',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='swipe_out_at',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
